package app.amisles.hanime.feature.search

/**
 * 官网搜索页「内容标签」全集
 * [SearchTag.value] 为官网原值（用于拼 URL 参数 tags[]=），[SearchTag.label] 为界面展示名。
 */
data class SearchTag(
    val value: String,
    val label: String
)

data class SearchTagGroup(
    val category: String,
    val tags: List<SearchTag>
)

object SearchTagCatalog {
    val groups: List<SearchTagGroup> = listOf(
        SearchTagGroup(
            category = "影片属性",
            tags = listOf(
                SearchTag(value = "無碼", label = "无码"),
                SearchTag(value = "AI解碼", label = "AI解码"),
                SearchTag(value = "中文字幕", label = "中文字幕"),
                SearchTag(value = "中文配音", label = "中文配音"),
                SearchTag(value = "同人作品", label = "同人作品"),
                SearchTag(value = "斷面圖", label = "断面图"),
                SearchTag(value = "ASMR", label = "ASMR"),
                SearchTag(value = "1080p", label = "1080p"),
                SearchTag(value = "60FPS", label = "60FPS")
            )
        ),
        SearchTagGroup(
            category = "人物关系",
            tags = listOf(
                SearchTag(value = "近親", label = "近亲"),
                SearchTag(value = "姐", label = "姐"),
                SearchTag(value = "妹", label = "妹"),
                SearchTag(value = "母", label = "母"),
                SearchTag(value = "女兒", label = "女儿"),
                SearchTag(value = "師生", label = "师生"),
                SearchTag(value = "情侶", label = "情侣"),
                SearchTag(value = "青梅竹馬", label = "青梅竹马"),
                SearchTag(value = "同事", label = "同事")
            )
        ),
        SearchTagGroup(
            category = "角色设定",
            tags = listOf(
                SearchTag(value = "JK", label = "JK"),
                SearchTag(value = "處女", label = "处女"),
                SearchTag(value = "御姐", label = "御姐"),
                SearchTag(value = "熟女", label = "熟女"),
                SearchTag(value = "人妻", label = "人妻"),
                SearchTag(value = "女教師", label = "女教师"),
                SearchTag(value = "男教師", label = "男教师"),
                SearchTag(value = "女醫生", label = "女医生"),
                SearchTag(value = "女病人", label = "女病人"),
                SearchTag(value = "護士", label = "护士"),
                SearchTag(value = "OL", label = "OL"),
                SearchTag(value = "女警", label = "女警"),
                SearchTag(value = "大小姐", label = "大小姐"),
                SearchTag(value = "偶像", label = "偶像"),
                SearchTag(value = "女僕", label = "女仆"),
                SearchTag(value = "巫女", label = "巫女"),
                SearchTag(value = "魔女", label = "魔女"),
                SearchTag(value = "修女", label = "修女"),
                SearchTag(value = "風俗娘", label = "风俗娘"),
                SearchTag(value = "公主", label = "公主"),
                SearchTag(value = "女忍者", label = "女忍者"),
                SearchTag(value = "女戰士", label = "女战士"),
                SearchTag(value = "女騎士", label = "女骑士"),
                SearchTag(value = "魔法少女", label = "魔法少女"),
                SearchTag(value = "異種族", label = "异种族"),
                SearchTag(value = "天使", label = "天使"),
                SearchTag(value = "妖精", label = "妖精"),
                SearchTag(value = "魔物娘", label = "魔物娘"),
                SearchTag(value = "魅魔", label = "魅魔"),
                SearchTag(value = "吸血鬼", label = "吸血鬼"),
                SearchTag(value = "女鬼", label = "女鬼"),
                SearchTag(value = "獸娘", label = "兽娘"),
                SearchTag(value = "福瑞", label = "福瑞"),
                SearchTag(value = "乳牛", label = "乳牛"),
                SearchTag(value = "機械娘", label = "机械娘"),
                SearchTag(value = "碧池", label = "碧池"),
                SearchTag(value = "痴女", label = "痴女"),
                SearchTag(value = "雌小鬼", label = "雌小鬼"),
                SearchTag(value = "不良少女", label = "不良少女"),
                SearchTag(value = "傲嬌", label = "傲娇"),
                SearchTag(value = "病嬌", label = "病娇"),
                SearchTag(value = "無口", label = "无口"),
                SearchTag(value = "無表情", label = "无表情"),
                SearchTag(value = "眼神死", label = "眼神死"),
                SearchTag(value = "正太", label = "正太"),
                SearchTag(value = "偽娘", label = "伪娘"),
                SearchTag(value = "扶他", label = "扶他")
            )
        ),
        SearchTagGroup(
            category = "外貌身材",
            tags = listOf(
                SearchTag(value = "短髮", label = "短发"),
                SearchTag(value = "馬尾", label = "马尾"),
                SearchTag(value = "雙馬尾", label = "双马尾"),
                SearchTag(value = "丸子頭", label = "丸子头"),
                SearchTag(value = "巨乳", label = "巨乳"),
                SearchTag(value = "乳環", label = "乳环"),
                SearchTag(value = "舌環", label = "舌环"),
                SearchTag(value = "貧乳", label = "贫乳"),
                SearchTag(value = "黑皮膚", label = "黑皮肤"),
                SearchTag(value = "曬痕", label = "晒痕"),
                SearchTag(value = "眼鏡娘", label = "眼镜娘"),
                SearchTag(value = "獸耳", label = "兽耳"),
                SearchTag(value = "尖耳朵", label = "尖耳朵"),
                SearchTag(value = "異色瞳", label = "异色瞳"),
                SearchTag(value = "美人痣", label = "美人痣"),
                SearchTag(value = "肌肉女", label = "肌肉女"),
                SearchTag(value = "白虎", label = "白虎"),
                SearchTag(value = "陰毛", label = "阴毛"),
                SearchTag(value = "腋毛", label = "腋毛"),
                SearchTag(value = "大屌", label = "大屌"),
                SearchTag(value = "黑屌", label = "黑屌"),
                SearchTag(value = "著衣", label = "着衣"),
                SearchTag(value = "水手服", label = "水手服"),
                SearchTag(value = "體操服", label = "体操服"),
                SearchTag(value = "泳裝", label = "泳装"),
                SearchTag(value = "比基尼", label = "比基尼"),
                SearchTag(value = "死庫水", label = "死库水"),
                SearchTag(value = "和服", label = "和服"),
                SearchTag(value = "兔女郎", label = "兔女郎"),
                SearchTag(value = "圍裙", label = "围裙"),
                SearchTag(value = "啦啦隊", label = "啦啦队"),
                SearchTag(value = "絲襪", label = "丝袜"),
                SearchTag(value = "吊襪帶", label = "吊袜带"),
                SearchTag(value = "熱褲", label = "热裤"),
                SearchTag(value = "迷你裙", label = "迷你裙"),
                SearchTag(value = "性感內衣", label = "性感内衣"),
                SearchTag(value = "緊身衣", label = "紧身衣"),
                SearchTag(value = "丁字褲", label = "丁字裤"),
                SearchTag(value = "高跟鞋", label = "高跟鞋"),
                SearchTag(value = "睡衣", label = "睡衣"),
                SearchTag(value = "婚紗", label = "婚纱"),
                SearchTag(value = "旗袍", label = "旗袍"),
                SearchTag(value = "古裝", label = "古装"),
                SearchTag(value = "哥德", label = "哥德"),
                SearchTag(value = "口罩", label = "口罩"),
                SearchTag(value = "刺青", label = "刺青"),
                SearchTag(value = "淫紋", label = "淫纹"),
                SearchTag(value = "身體寫字", label = "身体写字")
            )
        ),
        SearchTagGroup(
            category = "情境场所",
            tags = listOf(
                SearchTag(value = "校園", label = "校园"),
                SearchTag(value = "教室", label = "教室"),
                SearchTag(value = "圖書館", label = "图书馆"),
                SearchTag(value = "保健室", label = "保健室"),
                SearchTag(value = "體育倉庫", label = "体育仓库"),
                SearchTag(value = "游泳池", label = "游泳池"),
                SearchTag(value = "愛情賓館", label = "爱情宾馆"),
                SearchTag(value = "醫院", label = "医院"),
                SearchTag(value = "辦公室", label = "办公室"),
                SearchTag(value = "浴室", label = "浴室"),
                SearchTag(value = "窗邊", label = "窗边"),
                SearchTag(value = "公共廁所", label = "公共厕所"),
                SearchTag(value = "公眾場合", label = "公众场合"),
                SearchTag(value = "戶外野戰", label = "户外野战"),
                SearchTag(value = "電車", label = "电车"),
                SearchTag(value = "車震", label = "车震"),
                SearchTag(value = "遊艇", label = "游艇"),
                SearchTag(value = "露營帳篷", label = "露营帐篷"),
                SearchTag(value = "電影院", label = "电影院"),
                SearchTag(value = "健身房", label = "健身房"),
                SearchTag(value = "沙灘", label = "沙滩"),
                SearchTag(value = "溫泉", label = "温泉"),
                SearchTag(value = "夜店", label = "夜店"),
                SearchTag(value = "監獄", label = "监狱"),
                SearchTag(value = "教堂", label = "教堂")
            )
        ),
        SearchTagGroup(
            category = "故事剧情",
            tags = listOf(
                SearchTag(value = "純愛", label = "纯爱"),
                SearchTag(value = "戀愛喜劇", label = "恋爱喜剧"),
                SearchTag(value = "後宮", label = "后宫"),
                SearchTag(value = "十指緊扣", label = "十指紧扣"),
                SearchTag(value = "開大車", label = "开大车"),
                SearchTag(value = "NTR", label = "NTR"),
                SearchTag(value = "精神控制", label = "精神控制"),
                SearchTag(value = "藥物", label = "药物"),
                SearchTag(value = "痴漢", label = "痴汉"),
                SearchTag(value = "阿嘿顏", label = "阿嘿颜"),
                SearchTag(value = "哭泣", label = "哭泣"),
                SearchTag(value = "精神崩潰", label = "精神崩溃"),
                SearchTag(value = "獵奇", label = "猎奇"),
                SearchTag(value = "BDSM", label = "BDSM"),
                SearchTag(value = "綑綁", label = "捆绑"),
                SearchTag(value = "眼罩", label = "眼罩"),
                SearchTag(value = "項圈", label = "项圈"),
                SearchTag(value = "調教", label = "调教"),
                SearchTag(value = "異物插入", label = "异物插入"),
                SearchTag(value = "尋歡洞", label = "寻欢洞"),
                SearchTag(value = "肉便器", label = "肉便器"),
                SearchTag(value = "性奴隸", label = "性奴隶"),
                SearchTag(value = "胃凸", label = "胃凸"),
                SearchTag(value = "強制", label = "强制"),
                SearchTag(value = "輪姦", label = "轮奸"),
                SearchTag(value = "凌辱", label = "凌辱"),
                SearchTag(value = "性暴力", label = "性暴力"),
                SearchTag(value = "逆強制", label = "逆强制"),
                SearchTag(value = "女王樣", label = "女王样"),
                SearchTag(value = "榨精", label = "榨精"),
                SearchTag(value = "母女丼", label = "母女丼"),
                SearchTag(value = "姐妹丼", label = "姐妹丼"),
                SearchTag(value = "出軌", label = "出轨"),
                SearchTag(value = "醉酒", label = "醉酒"),
                SearchTag(value = "攝影", label = "摄影"),
                SearchTag(value = "睡眠姦", label = "睡眠奸"),
                SearchTag(value = "機械姦", label = "机械奸"),
                SearchTag(value = "蟲姦", label = "虫奸"),
                SearchTag(value = "性轉換", label = "性转换"),
                SearchTag(value = "百合", label = "百合"),
                SearchTag(value = "耽美", label = "耽美"),
                SearchTag(value = "時間停止", label = "时间停止"),
                SearchTag(value = "異世界", label = "异世界"),
                SearchTag(value = "怪獸", label = "怪兽"),
                SearchTag(value = "哥布林", label = "哥布林"),
                SearchTag(value = "世界末日", label = "世界末日")
            )
        ),
        SearchTagGroup(
            category = "性交体位",
            tags = listOf(
                SearchTag(value = "手交", label = "手交"),
                SearchTag(value = "指交", label = "指交"),
                SearchTag(value = "玩乳頭", label = "玩乳头"),
                SearchTag(value = "乳交", label = "乳交"),
                SearchTag(value = "乳頭交", label = "乳头交"),
                SearchTag(value = "肛交", label = "肛交"),
                SearchTag(value = "雙洞齊下", label = "双洞齐下"),
                SearchTag(value = "腳交", label = "脚交"),
                SearchTag(value = "素股", label = "素股"),
                SearchTag(value = "拳交", label = "拳交"),
                SearchTag(value = "3P", label = "3P"),
                SearchTag(value = "群交", label = "群交"),
                SearchTag(value = "口交", label = "口交"),
                SearchTag(value = "跪舔", label = "跪舔"),
                SearchTag(value = "深喉嚨", label = "深喉咙"),
                SearchTag(value = "口爆", label = "口爆"),
                SearchTag(value = "吞精", label = "吞精"),
                SearchTag(value = "舔蛋蛋", label = "舔蛋蛋"),
                SearchTag(value = "舔穴", label = "舔穴"),
                SearchTag(value = "69", label = "69"),
                SearchTag(value = "自慰", label = "自慰"),
                SearchTag(value = "腋交", label = "腋交"),
                SearchTag(value = "舔腋下", label = "舔腋下"),
                SearchTag(value = "髮交", label = "发交"),
                SearchTag(value = "舔耳朵", label = "舔耳朵"),
                SearchTag(value = "舔腳", label = "舔脚"),
                SearchTag(value = "內射", label = "内射"),
                SearchTag(value = "外射", label = "外射"),
                SearchTag(value = "顏射", label = "颜射"),
                SearchTag(value = "潮吹", label = "潮吹"),
                SearchTag(value = "懷孕", label = "怀孕"),
                SearchTag(value = "噴奶", label = "喷奶"),
                SearchTag(value = "放尿", label = "放尿"),
                SearchTag(value = "排便", label = "排便"),
                SearchTag(value = "騎乘位", label = "骑乘位"),
                SearchTag(value = "背後位", label = "背后位"),
                SearchTag(value = "側面位", label = "侧面位"),
                SearchTag(value = "顏面騎乘", label = "颜面骑乘"),
                SearchTag(value = "火車便當", label = "火车便当"),
                SearchTag(value = "一字馬", label = "一字马"),
                SearchTag(value = "性玩具", label = "性玩具"),
                SearchTag(value = "飛機杯", label = "飞机杯"),
                SearchTag(value = "跳蛋", label = "跳蛋"),
                SearchTag(value = "毒龍鑽", label = "毒龙钻"),
                SearchTag(value = "觸手", label = "触手"),
                SearchTag(value = "獸交", label = "兽交"),
                SearchTag(value = "頸手枷", label = "颈手枷"),
                SearchTag(value = "扯頭髮", label = "扯头发"),
                SearchTag(value = "掐脖子", label = "掐脖子"),
                SearchTag(value = "打屁股", label = "打屁股"),
                SearchTag(value = "肉棒打臉", label = "肉棒打脸"),
                SearchTag(value = "陰道外翻", label = "阴道外翻"),
                SearchTag(value = "男乳首責", label = "男乳首责"),
                SearchTag(value = "接吻", label = "接吻"),
                SearchTag(value = "舌吻", label = "舌吻"),
                SearchTag(value = "POV", label = "POV")
            )
        )
    )

    private val labelMap: Map<String, String> = groups.flatMap { g -> g.tags.map { it.value to it.label } }.toMap()

    fun findLabel(value: String): String = labelMap[value] ?: value
}
